### PR TITLE
[PRD-5] Move openpath konnector into service

### PR DESCRIPTION
**Pull request by paultranvan**
This new `fetchOpenPathTrips` service is basically a port of the openpath konnector: https://github.com/konnectors/openpath
We move the logic here for several reasons:

- This konnector was confusing: during the onboarding, the konnector is
  automatically configured, but it was still appearing on the Home,
  while the user did not know what is was about.
- A side-effect of the previous reason is that the user was missing all
  the onboarded Home, with an explanation of the konnectors, when none
  is installed.
- The code logic will now be available in one place, CoachCO2, which is
  much convenient to factorize some code.
- The `timeseriesWithoutAggregateMigration` service will become useless,
  as the "konnector" service will be able to correctly format the data,
  taking advantage of code factorization.

```
### ✨ Features

* Fetch trips from service 

### 🐛 Bug Fixes

*

### 🔧 Tech

*
```

### CODE REVIEW

**Comment by zatteo** [comment]
We must also remove the "You must install OpenPath konnector" logic.

image

See OpenPathKonnectorDialog and showOpenPathKonnectorDialog
https://github.com/cozy/coachCO2/blob/59c6ba5cc2f40d45354c3af9f3e1f73aa0ab21ad/src/components/GeolocationTracking/InstallOpenPathKonnectorDialog.jsx#L9

**Comment by zatteo** [comment]
Now that we can access the token from the service, maybe we should not recreate the account every time the flagship app loses the token stored locally.

**Comment by paultranvan** [comment]
> We must also remove the "You must install OpenPath konnector" logic.
> screen
> 
> See OpenPathKonnectorDialog and showOpenPathKonnectorDialog
> 
> https://github.com/cozy/coachCO2/blob/59c6ba5cc2f40d45354c3af9f3e1f73aa0ab21ad/src/components/GeolocationTracking/InstallOpenPathKonnectorDialog.jsx#L9

Absolutely thanks, see c2e62a414ae30fa44a39b5316eaa99fc7b887196

**Review by zatteo — APPROVED** [review]

**Comment by paultranvan** [comment]
> Now that we can access the token from the service, maybe we should not recreate the account every time the flagship app loses the token stored locally.

Right, we need to properly handle revocation, but for now, let's create an account only when the device name is different from the existing one

**Pull request merged**
